project:
  type: book
  output-dir: docs
  # output-dir: pdfs
  preview:
    port: 7771
    browser: false
  resources:
    - "data/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!to_do.qmd"

lang: ko-KR

book:
  title: "챗GPT 쿼토(Quarto)"
  reader-mode: true
  subtitle: "인공지능 시대 데이터 과학 저작 도구"

  page-footer:
    left: |
      챗GPT 쿼토 책은 소프트웨어 카펜트리 Introduction to Reproducible Publications with Quarto 번역한 것이 포함되어 있습니다.
    right: |
      순수하게 <a href="https://quarto.org/">쿼토(Quarto)</a>로 제작되었습니다.

  cover-image: images/book_cover.jpg
  favicon: images/logo.png
  site-url: https://r2bit.com/gpt-quarto/
  repo-url: https://github.com/bit2r/gpt-quarto/
  repo-branch: main
  repo-actions: [edit, issue]

  google-analytics: "UA-229551680-1"
  author:
    - name: "이광춘"
      affiliations: "공익법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"
  chapters:
    # - acknowledgments.qmd
    - index.qmd

    - part: "시작을 위한 준비"
      chapters:
        - setup_reproducible.qmd    # OK
        - setup_markdown_mess.qmd   # 
        - setup_quarto.qmd           # OK
        - setup.qmd                  # OK
        
    - part: "저작 레고 부품"
      chapters:
        - part_components.qmd          # OK
        - part_markdown.qmd            # OK
        - part_code.qmd          # OK        

    - part: "템플릿과 테마"
      chapters:
        - theme_fonts.qmd         # OK
        - theme_colors.qmd        # OK
        - theme_ggplot.qmd        # OK
        - theme_gt.qmd            # OK

    - part: "저작물"
      chapters:
      - dw_website.qmd          # Blog 추가
      - dw_slideshow.qmd        # OK
      - dw_dashboard.qmd        # flexdashboard 변환
      - dw_book.qmd             # OK
      - dw_params.qmd           # flexdashboard 변환      

    - part: "챗GPT 활용"
      chapters:
      - gpt_writing.qmd    #
      - gpt_resume.qmd        #
      - gpt_case_study.qmd    #      

    - references.qmd     # O

format:
  html:
    mermaid:
      theme: neutral # https://quarto.org/docs/authoring/diagrams.html#mermaid-theming 
    theme: 
      - cosmo
      - r2bit.scss      
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap
    code-link: true

    author-meta: "이광춘"
    include-in-header: "plausible.html"
    callout-appearance: simple
    
    # 마크다운 표 캡션 위치
    tbl-cap-location: bottom

bibliography: references.bib
link-citations: false

engine: knitr

filters:
   - lightbox
   - parse-latex
   - include-code-files   
lightbox: auto

code-annotations: hover

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    code-overflow: code-overflow
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
editor_options:
  chunk_output_type: console

editor: 
  markdown: 
    wrap: 72
    